substitutions:
  _APP_NAME: gdgdemo-app
  _KUSTOMIZE_OVERLAY: prod
  _GKE_ZONE: asia-southeast1-a
  _GKE_CLUSTER: gdgkl-demo
  
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Docker'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    docker build -t ${_APP_NAME}:${SHORT_SHA} \
      --build-arg COMMIT=${SHORT_SHA} \
      . && \
    #tag to both registry/image:sha and registry/image:latest
    docker tag ${_APP_NAME}:${SHORT_SHA} \
      asia.gcr.io/$PROJECT_ID/${_APP_NAME}:${SHORT_SHA} && \
    docker tag ${_APP_NAME}:${SHORT_SHA} \
      asia.gcr.io/$PROJECT_ID/${_APP_NAME}:latest && \

    docker push asia.gcr.io/$PROJECT_ID/${_APP_NAME}:${SHORT_SHA} && \
    docker push asia.gcr.io/$PROJECT_ID/${_APP_NAME}:latest

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Perform credential decryption'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd /workspace/k8s-repo && \
    gcloud kms decrypt --plaintext-file=overlays/${_KUSTOMIZE_OVERLAY}/secrets/secrets.env \
      --ciphertext-file=overlays/${_KUSTOMIZE_OVERLAY}/secrets/secrets.env.enc \
      --keyring=gdg-demo-keyring \
      --key=gdg-demo-key \
      --location=global
  volumes:
  - name: k8s-repo
    path: /workspace/k8s-repo

- name: 'asia.gcr.io/$PROJECT_ID/kustomize'
  id: 'Update GKE deployment'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd /workspace/k8s-repo && \
    gcloud container clusters get-credentials ${_GKE_CLUSTER} && \
    kustomize build "overlays/${_KUSTOMIZE_OVERLAY}" | kubectl apply -f - && \
    kubectl rollout status deploy/${_KUSTOMIZE_OVERLAY}-gdg-app \
      --namespace=${_KUSTOMIZE_OVERLAY} \
      --timeout=300s
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  volumes:
  - name: k8s-repo
    path: /workspace/k8s-repo